List<Map<String, dynamic>> ticketList = [
  {
    'from': {'code': 'NYC', 'name': 'New-York'},
    'to': {'code': 'LDN', 'name': 'London'},
    'flying_time': '8H 30M',
    'date': '1 May',
    'departure_time': '08:00 AM',
    'number': '23',
  },
  {
    'from': {'code': 'SFO', 'name': 'San Francisco'},
    'to': {'code': 'TYO', 'name': 'Tokyo'},
    'flying_time': '11H 15M',
    'date': '3 May',
    'departure_time': '10:45 AM',
    'number': '42',
  },
  {
    'from': {'code': 'PAR', 'name': 'Paris'},
    'to': {'code': 'BER', 'name': 'Berlin'},
    'flying_time': '1H 50M',
    'date': '5 May',
    'departure_time': '06:30 PM',
    'number': '15',
  },
  {
    'from': {'code': 'DXB', 'name': 'Dubai'},
    'to': {'code': 'SYD', 'name': 'Sydney'},
    'flying_time': '13H 40M',
    'date': '10 May',
    'departure_time': '01:20 AM',
    'number': '87',
  },
  {
    'from': {'code': 'CAI', 'name': 'Cairo'},
    'to': {'code': 'IST', 'name': 'Istanbul'},
    'flying_time': '2H 10M',
    'date': '12 May',
    'departure_time': '09:15 AM',
    'number': '34',
  },
  {
    'from': {'code': 'MUM', 'name': 'Mumbai'},
    'to': {'code': 'SIN', 'name': 'Singapore'},
    'flying_time': '5H 30M',
    'date': '15 May',
    'departure_time': '03:00 PM',
    'number': '76',
  },
];
